repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        # Trims trailing whitespace.
    -   id: end-of-file-fixer
        # Makes sure files end in a newline and only a newline.
    -   id: check-yaml
        # Attempts to load all yaml files to verify syntax.
    -   id: debug-statements
        # Check for debugger imports and py37+ breakpoint() calls in python source.
    -   id: name-tests-test
        args: [--pytest-test-first]
        # verifies that test files are named correctly. ensure tests match .*_test\.py
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
    -   id: add-trailing-comma
        # A tool (and pre-commit hook) to automatically add trailing commas to calls and literals.
        args: [--py36-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
    -   id: pyupgrade
        # A tool (and pre-commit hook) to automatically upgrade syntax for newer versions of the language.
        args: [--py38-plus]
        # Mirror of autopep8 package for pre-commit.
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]

